<?php
// $Id: commentaccess.install,v 1.1 2011/01/27 18:29:19 rschwab Exp $

/**
 * @file
 * Install and uninstall functions for Comment Access
 */

/**
 * Implementation of hook_uninstall().
 */
function commentaccess_uninstall() {
  variable_del('commentaccess_approval_msg');
  variable_del('commentaccess_approval_php');
  variable_del('commentaccess_mail_message');
  variable_del('commentaccess_mail_subject');
}
